### ISSUE TITLE
Error after init config input

### ISSUE THREAD

**Issue by ruisilva450** [bhamodi/facebook-online-friend-tracker#6]
I'm encountering the following error:

```
Initializing Chrome WebDriver...
Traceback (most recent call last):
  File "/usr/local/bin/facebook-online-friend-tracker", line 9, in <module>
    load_entry_point('facebook-online-friend-tracker==2.0.0', 'console_scripts', 'facebook-online-friend-tracker')()
  File "/usr/local/lib/python2.7/dist-packages/src/main.py", line 68, in main
    driver = webdriver.Chrome()
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/chrome/webdriver.py", line 61, in __init__
    self.service.start()
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/common/service.py", line 62, in start
    stdout=self.log_file, stderr=self.log_file)
  File "/usr/lib/python2.7/subprocess.py", line 679, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1259, in _execute_child
    raise child_exception
OSError: [Errno 8] Exec format error
Exception AttributeError: "'Service' object has no attribute 'process'" in <bound method Service.__del__ of <selenium.webdriver.chrome.service.Service object at 0xe6fa50>> ignored
```

Any hint about what is causing this?

**Comment by bhamodi** [comment]
Hi @ruisilva450, are you still able to repro this error?

**Comment by jasonsheil** [comment]
Having the same issue

```
Initializing Chrome WebDriver...
Traceback (most recent call last):
  File "/home/jasonshe/.local/bin/facebook-online-friend-tracker", line 8, in <module>
    load_entry_point('facebook-online-friend-tracker==2.0.0', 'console_scripts', 'facebook-online-friend-tracker')()
  File "/home/jasonshe/.local/lib/python2.7/site-packages/src/main.py", line 68, in main
    driver = webdriver.Chrome()
  File "/home/jasonshe/.local/lib/python2.7/site-packages/selenium/webdriver/chrome/webdriver.py", line 62, in __init__
    self.service.start()
  File "/home/jasonshe/.local/lib/python2.7/site-packages/selenium/webdriver/common/service.py", line 71, in start
    os.path.basename(self.path), self.start_error_message)
selenium.common.exceptions.WebDriverException: Message: 'chromedriver' executable needs to be in PATH. Please see https://sites.google.com/a/chromium.org/chromedriver/home

Exception AttributeError: "'Service' object has no attribute 'process'" in <bound method Service.__del__ of <selenium.webdriver.chrome.service.Service object at 0x7f547e7635d0>> ignored
```
